[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#3a86ff"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1f1f1f"
textColor = "#ffffff"
font = "sans serif"
